[versions]
activitycompose = "1.5.0"
compose = "1.1.1"
corektx = "1.8.0"
gradleplugin = "7.2.1"
gradleversions = "0.42.0"
hilt = "2.42"
junit = "4.13.2"
kotlin = "1.6.10"
runtimektx = "2.5.0"
versioncatalogupdate = "0.5.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activitycompose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "corektx" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "runtimektx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradleversions" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versioncatalogupdate" }
